'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');

const configSchema = require('../config.schema.json');
const { normalizeWeatherConfig } = require('../lib/config/weather-config');
const { createMappingKey } = require('../lib/mappings/mapping-identity');
const { normalizeMappings } = require('../lib/mappings/mapping-normalizer');
const { JsonSourceFormat, parseJsonPath } = require('../lib/sources/json-source-format');
const {
  SourceFormatRegistry,
  createDefaultSourceFormatRegistry,
} = require('../lib/sources/source-format-registry');
const { SUPPORTED_WEATHER_UNITS } = require('../lib/units/weather-unit-definitions');
const {
  WeatherUnitRegistry,
  createDefaultWeatherUnitRegistry,
} = require('../lib/units/weather-unit-registry');

/**
 * <summary>
 * Creates deterministic HAP UUID support for production unit-registry contract tests without loading Homebridge.
 * </summary>
 * @returns {object} Minimal HAP namespace whose UUID output exposes the supplied seed.
 */
function createHapDouble() {
  return {
    uuid: {
      /**
       * <summary>
       * Converts one stable plugin seed into a readable deterministic UUID double.
       * </summary>
       * @param {string} seed Stable UUID seed generated by production code.
       * @returns {string} Deterministic test UUID.
       */
      generate(seed) {
        return `uuid:${seed}`;
      },
    },
  };
}

/**
 * <summary>
 * Converts a source value to a finite number for reusable test unit definitions.
 * </summary>
 * @param {unknown} value Raw source value.
 * @returns {number} Finite numeric representation of the source value.
 * @throws {TypeError} When the source value is not finite.
 */
function normalizeNumber(value) {
  const normalized = Number(value);
  if (!Number.isFinite(normalized)) {
    throw new TypeError('Expected a finite number');
  }
  return normalized;
}

/**
 * <summary>
 * Creates one complete test-only unit definition for registry and mapping validation tests.
 * </summary>
 * @param {string} [unit] Compact unit identifier exposed in mapping configuration.
 * @returns {object} Mutable definition suitable for registry construction and invalid-definition mutations.
 */
function createTestDefinition(unit = 'test-unit') {
  return {
    unit,
    automationKind: 'numeric',
    characteristicUuid: `uuid:test-unit:${unit}`,
    characteristicProps: { format: 'float', unit, perms: ['pr', 'ev'] },
    normalize: normalizeNumber,
    neutralValue: -1,
  };
}

/**
 * <summary>
 * Creates a logger double that records warning messages for mapping and configuration assertions.
 * </summary>
 * @returns {{warnings: string[], warn: Function}} Logger double and captured warning collection.
 */
function createWarningLogger() {
  const warnings = [];

  /**
   * <summary>
   * Records one warning emitted by configuration normalization.
   * </summary>
   * @param {string} message Warning text.
   * @returns {void}
   * @sideEffect Appends the message to the logger double's warning collection.
   */
  function warn(message) {
    warnings.push(message);
  }

  return { warnings, warn };
}

/**
 * <summary>
 * Verifies the production unit catalog, runtime registry, and public schema expose the exact same ordered symbols.
 * This prevents a unit from being selectable but unusable, or usable at runtime but absent from the editor.
 * </summary>
 * @returns {void}
 */
function unitCatalogAndSchemaRemainSynchronized() {
  const registry = createDefaultWeatherUnitRegistry(createHapDouble());
  const registryUnits = registry.list().map(
    /**
     * <summary>
     * Selects the public compact unit identifier from one immutable runtime definition.
     * </summary>
     * @param {object} definition Unit definition owned by the production registry.
     * @returns {string} Compact unit symbol.
     */
    function selectUnit(definition) {
      return definition.unit;
    },
  );
  const mappingSchema = configSchema.schema.properties.mappings.items;

  assert.deepEqual(registryUnits, Array.from(SUPPORTED_WEATHER_UNITS));
  assert.deepEqual(mappingSchema.properties.unit.enum, Array.from(SUPPORTED_WEATHER_UNITS));
  assert.deepEqual(Object.keys(mappingSchema.properties), ['name', 'unit', 'path']);
  assert.deepEqual(mappingSchema.required, ['name', 'unit', 'path']);
  assert.equal(mappingSchema.additionalProperties, false);
  assert.equal(Object.isFrozen(registry.list()), true);
  assert.equal(Object.isFrozen(registry.get('°C')), true);
  assert.equal(Object.isFrozen(registry.get('°C').characteristicProps), true);
}

/**
 * <summary>
 * Verifies explicit unit definitions are validated, copied, frozen, and protected from duplicate unit symbols.
 * </summary>
 * @returns {void}
 */
function weatherUnitRegistryValidatesDefinitions() {
  const registry = new WeatherUnitRegistry([createTestDefinition()]);
  const storedDefinition = registry.get('test-unit');

  assert.equal(registry.has('test-unit'), true);
  assert.equal(storedDefinition.neutralValue, -1);
  assert.equal(Object.isFrozen(storedDefinition), true);
  assert.equal(Object.isFrozen(storedDefinition.characteristicProps), true);

  /**
   * <summary>
   * Attempts to construct a registry containing two definitions with the same unit identifier.
   * </summary>
   * @returns {void}
   */
  function createDuplicateRegistry() {
    new WeatherUnitRegistry([createTestDefinition(), createTestDefinition()]);
  }

  /**
   * <summary>
   * Attempts to construct a definition without its required explicit neutral value.
   * </summary>
   * @returns {void}
   */
  function createRegistryWithoutNeutralValue() {
    const definition = createTestDefinition();
    delete definition.neutralValue;
    new WeatherUnitRegistry([definition]);
  }

  /**
   * <summary>
   * Attempts to construct a definition whose normalization contract is not callable.
   * </summary>
   * @returns {void}
   */
  function createRegistryWithInvalidNormalizer() {
    const definition = createTestDefinition();
    definition.normalize = 'invalid';
    new WeatherUnitRegistry([definition]);
  }

  assert.throws(createDuplicateRegistry, /Duplicate weather unit definition/);
  assert.throws(createRegistryWithoutNeutralValue, /neutralValue/);
  assert.throws(createRegistryWithInvalidNormalizer, /normalize function/);
}

/**
 * <summary>
 * Verifies dot paths, numeric array indexes, JSON Pointer paths, RFC 6901 escapes, and missing values.
 * </summary>
 * @returns {void}
 */
function jsonSourceReadsSupportedPaths() {
  const format = new JsonSourceFormat();
  const document = {
    observations: [{ metric: { temp: 18 }, 'wind/speed': 4, 'tilde~value': 7 }],
  };

  assert.deepEqual(parseJsonPath('observations[0].metric.temp'), [
    'observations',
    '0',
    'metric',
    'temp',
  ]);
  assert.equal(format.read(document, 'observations[0].metric.temp'), 18);
  assert.equal(format.read(document, '/observations/0/metric/temp'), 18);
  assert.equal(format.read(document, '/observations/0/wind~1speed'), 4);
  assert.equal(format.read(document, '/observations/0/tilde~0value'), 7);
  assert.equal(format.read(document, 'observations[1].metric.temp'), undefined);
}

/**
 * <summary>
 * Asserts that one unsafe or malformed JSON mapping path is rejected by the parser.
 * </summary>
 * @param {unknown} path Candidate mapping path.
 * @param {RegExp} expectedMessage Expected validation message fragment.
 * @returns {void}
 */
function assertJsonPathRejected(path, expectedMessage) {
  /**
   * <summary>
   * Parses the candidate path so the assertion can observe the validation error.
   * </summary>
   * @returns {void}
   */
  function parseRejectedPath() {
    parseJsonPath(path);
  }

  assert.throws(parseRejectedPath, expectedMessage);
}

/**
 * <summary>
 * Verifies malformed syntax and prototype-related segments are rejected before document traversal.
 * </summary>
 * @returns {void}
 */
function jsonSourceRejectsUnsafeAndInvalidPaths() {
  assertJsonPathRejected('', /non-empty strings/);
  assertJsonPathRejected('observations..temp', /empty property/);
  assertJsonPathRejected('observations[-1]', /non-negative numeric/);
  assertJsonPathRejected('observations[0', /unclosed array index/);
  assertJsonPathRejected('/observations/~2temp', /invalid escape/);
  assertJsonPathRejected('/observations/__proto__/value', /cannot contain __proto__/);
  assertJsonPathRejected('observations.constructor.value', /cannot contain constructor/);
}

/**
 * <summary>
 * Supplies a non-JSON source format implementation to prove the format registry is independently extensible.
 * </summary>
 */
class TextSourceFormat {
  /**
   * <summary>
   * Returns the source response unchanged.
   * </summary>
   * @param {string} text Raw response text.
   * @returns {string} Unchanged response text.
   */
  parse(text) {
    return text;
  }

  /**
   * <summary>
   * Accepts a non-empty field name for the test format.
   * </summary>
   * @param {string} path Configured field name.
   * @returns {void}
   * @throws {TypeError} When the field name is empty.
   */
  validatePath(path) {
    if (!path) {
      throw new TypeError('Text field names must not be empty');
    }
  }

  /**
   * <summary>
   * Resolves the whole test document for its single supported value path.
   * </summary>
   * @param {string} document Parsed text document.
   * @param {string} _path Accepted field name.
   * @returns {string} Parsed text document.
   */
  read(document, _path) {
    return document;
  }
}

/**
 * <summary>
 * Verifies custom source handlers can be registered without affecting the built-in JSON handler.
 * </summary>
 * @returns {void}
 */
function sourceFormatRegistrySupportsExtensions() {
  const registry = createDefaultSourceFormatRegistry();
  const textHandler = new TextSourceFormat();
  registry.register('text', textHandler);

  assert.equal(registry.has('json'), true);
  assert.equal(registry.get('text'), textHandler);
  assert.deepEqual(registry.list(), ['json', 'text']);

  /**
   * <summary>
   * Attempts to replace an already registered source type.
   * </summary>
   * @returns {void}
   */
  function registerDuplicateSourceType() {
    registry.register('text', new TextSourceFormat());
  }

  /**
   * <summary>
   * Attempts to register an incomplete source handler contract.
   * </summary>
   * @returns {void}
   */
  function registerIncompleteSourceHandler() {
    new SourceFormatRegistry([{ type: 'broken', handler: {} }]);
  }

  assert.throws(registerDuplicateSourceType, /already registered/);
  assert.throws(registerIncompleteSourceHandler, /requires a parse method/);
}

/**
 * <summary>
 * Verifies mappings may repeat one unit under distinct user names while an identical name-and-unit pair is rejected.
 * Invalid units, paths, and entries are skipped independently without changing valid mapping order.
 * </summary>
 * @returns {void}
 */
function mappingNormalizationUsesNameAndUnitIdentity() {
  const logger = createWarningLogger();
  const unitRegistry = new WeatherUnitRegistry([
    createTestDefinition('°C'),
    createTestDefinition('%'),
  ]);
  const mappings = normalizeMappings(
    [
      { name: ' Temperature ', unit: ' °C ', path: ' current.temperature_2m ' },
      { name: 'Dew point', unit: '°C', path: '/current/dew_point_2m' },
      { name: 'Temperature', unit: '°C', path: '/duplicate/path' },
      { name: 'Temperature', unit: '%', path: '/current/relative_humidity_2m' },
      { name: 'Unknown', unit: 'K', path: '/current/value' },
      { name: 'Broken path', unit: '%', path: 'observations[-1]' },
      null,
    ],
    { unitRegistry, formatHandler: new JsonSourceFormat(), log: logger },
  );

  assert.deepEqual(mappings, [
    {
      key: createMappingKey('Temperature', '°C'),
      name: 'Temperature',
      unit: '°C',
      path: 'current.temperature_2m',
    },
    {
      key: createMappingKey('Dew point', '°C'),
      name: 'Dew point',
      unit: '°C',
      path: '/current/dew_point_2m',
    },
    {
      key: createMappingKey('Temperature', '%'),
      name: 'Temperature',
      unit: '%',
      path: '/current/relative_humidity_2m',
    },
  ]);
  assert.notEqual(mappings[0].key, mappings[1].key);
  assert.equal(Object.isFrozen(mappings), true);
  assert.equal(Object.isFrozen(mappings[0]), true);
  assert.equal(logger.warnings.length, 4);
  assert.match(logger.warnings.join('\n'), /duplicates name Temperature with unit °C/);
  assert.match(logger.warnings.join('\n'), /unsupported unit K/);
  assert.match(logger.warnings.join('\n'), /invalid path/);
}

/**
 * <summary>
 * Verifies the hidden mapping key depends only on normalized name and unit, so correcting a provider path reuses
 * the same cached HomeKit service instead of creating a new identity.
 * </summary>
 * @returns {void}
 */
function mappingKeyRemainsStableAcrossPathChanges() {
  const options = {
    unitRegistry: new WeatherUnitRegistry([createTestDefinition('m/s')]),
    formatHandler: new JsonSourceFormat(),
    log: createWarningLogger(),
  };
  const firstMapping = normalizeMappings(
    [{ name: 'Wind at 10 m', unit: 'm/s', path: '/current/wind_speed_10m' }],
    options,
  )[0];
  const correctedMapping = normalizeMappings(
    [{ name: 'Wind at 10 m', unit: 'm/s', path: '/observations/wind/speed' }],
    options,
  )[0];

  assert.equal(firstMapping.key, correctedMapping.key);
  assert.notEqual(firstMapping.path, correctedMapping.path);
  assert.equal(firstMapping.key, createMappingKey('Wind at 10 m', 'm/s'));
  assert.equal(Object.prototype.hasOwnProperty.call(firstMapping, 'type'), false);
}

/**
 * <summary>
 * Verifies omitted user settings receive JSON, five-minute, Weather, blank-source, and empty-mapping defaults.
 * </summary>
 * @returns {void}
 */
function weatherConfigurationAppliesDefaults() {
  const dependencies = {
    sourceFormatRegistry: createDefaultSourceFormatRegistry(),
    unitRegistry: createDefaultWeatherUnitRegistry(createHapDouble()),
    log: createWarningLogger(),
  };
  const config = normalizeWeatherConfig({}, dependencies);

  assert.deepEqual(config, {
    sourceType: 'json',
    source: '',
    intervalMinutes: 5,
    name: 'Weather',
    mappings: [],
  });
  assert.equal(Object.isFrozen(config), true);

  const invalidIntervalConfig = normalizeWeatherConfig({ interval: 2.5 }, dependencies);
  assert.equal(invalidIntervalConfig.intervalMinutes, 5);
}

test('unit catalog, runtime registry, and schema stay synchronized', unitCatalogAndSchemaRemainSynchronized);
test('weather unit registry validates extension definitions', weatherUnitRegistryValidatesDefinitions);
test('JSON source format reads dot, array, and JSON Pointer paths', jsonSourceReadsSupportedPaths);
test('JSON source format rejects unsafe and malformed paths', jsonSourceRejectsUnsafeAndInvalidPaths);
test('source format registry supports independent extensions', sourceFormatRegistrySupportsExtensions);
test('mapping identity allows repeated units but rejects duplicate name and unit', mappingNormalizationUsesNameAndUnitIdentity);
test('mapping key remains stable when only the source path changes', mappingKeyRemainsStableAcrossPathChanges);
test('weather configuration applies documented defaults', weatherConfigurationAppliesDefaults);
