'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');

const {
  DUTCH_COMPASS_16_DIRECTIONS,
  normalizeCompass16Direction,
  normalizeDegreeDirection,
  convertCompass16ToDegrees,
  convertDegreesToCompass16,
} = require('../lib/units/wind-direction-converters');
const { createDefaultWeatherUnitRegistry } = require('../lib/units/weather-unit-registry');

/**
 * <summary>
 * Creates deterministic UUID support so production unit definitions can be inspected without loading Homebridge.
 * </summary>
 * @returns {object} Minimal HAP namespace containing a stable UUID generator.
 */
function createHapDouble() {
  return {
    uuid: {
      /**
       * <summary>
       * Converts a production UUID seed into a deterministic readable test value.
       * </summary>
       * @param {string} seed Stable UUID seed generated by the unit registry.
       * @returns {string} Deterministic test UUID.
       */
      generate(seed) {
        return `uuid:${seed}`;
      },
    },
  };
}

/**
 * <summary>
 * Verifies the canonical Dutch compass rose contains the correct clockwise 16-point sequence and converts every
 * sector center in both directions without loss.
 * </summary>
 * @returns {void}
 */
function compassCentersRoundTripAcrossAllDirections() {
  assert.deepEqual(DUTCH_COMPASS_16_DIRECTIONS, [
    'N', 'NNO', 'NO', 'ONO', 'O', 'OZO', 'ZO', 'ZZO',
    'Z', 'ZZW', 'ZW', 'WZW', 'W', 'WNW', 'NW', 'NNW',
  ]);

  for (let index = 0; index < DUTCH_COMPASS_16_DIRECTIONS.length; index += 1) {
    const direction = DUTCH_COMPASS_16_DIRECTIONS[index];
    const degrees = index * 22.5;
    assert.equal(convertCompass16ToDegrees(direction), degrees);
    assert.equal(convertDegreesToCompass16(degrees), direction);
  }
}

/**
 * <summary>
 * Verifies exact sector boundaries advance clockwise and that north correctly spans the zero-degree wraparound.
 * </summary>
 * @returns {void}
 */
function degreeConversionUsesCorrectSectorBoundaries() {
  assert.equal(convertDegreesToCompass16(0), 'N');
  assert.equal(convertDegreesToCompass16(11.249), 'N');
  assert.equal(convertDegreesToCompass16(11.25), 'NNO');
  assert.equal(convertDegreesToCompass16(33.749), 'NNO');
  assert.equal(convertDegreesToCompass16(33.75), 'NO');
  assert.equal(convertDegreesToCompass16(281.25), 'WNW');
  assert.equal(convertDegreesToCompass16(348.749), 'NNW');
  assert.equal(convertDegreesToCompass16(348.75), 'N');
  assert.equal(convertDegreesToCompass16(360), 'N');
}

/**
 * <summary>
 * Verifies international aliases and harmless formatting differences normalize to the Dutch compass notation.
 * </summary>
 * @returns {void}
 */
function internationalCompassAliasesNormalizeToDutch() {
  const aliases = [
    ['NNE', 'NNO'], ['NE', 'NO'], ['ENE', 'ONO'], ['E', 'O'],
    ['ESE', 'OZO'], ['SE', 'ZO'], ['SSE', 'ZZO'], ['S', 'Z'],
    ['SSW', 'ZZW'], ['SW', 'ZW'], ['WSW', 'WZW'], ['WNW', 'WNW'],
  ];

  for (const [source, expected] of aliases) {
    assert.equal(normalizeCompass16Direction(source), expected);
  }

  assert.equal(normalizeCompass16Direction(' n-n-w '), 'NNW');
  assert.equal(convertCompass16ToDegrees('ssw'), 202.5);
}

/**
 * <summary>
 * Asserts one converter rejects a supplied invalid source value with the expected controlled validation message.
 * </summary>
 * @param {Function} converter Wind-direction converter under test.
 * @param {unknown} value Invalid source value.
 * @param {RegExp} expectedMessage Expected validation-message fragment.
 * @returns {void}
 */
function assertDirectionValueRejected(converter, value, expectedMessage) {
  /**
   * <summary>
   * Invokes the selected converter with the enclosing invalid value for the rejection assertion.
   * </summary>
   * @returns {void}
   */
  function convertInvalidValue() {
    converter(value);
  }

  assert.throws(convertInvalidValue, expectedMessage);
}

/**
 * <summary>
 * Verifies malformed, variable, calm, missing, negative, and overflowing values cannot become a false direction.
 * </summary>
 * @returns {void}
 */
function invalidDirectionValuesAreRejected() {
  assertDirectionValueRejected(normalizeCompass16Direction, 'NWW', /supported abbreviation/);
  assertDirectionValueRejected(normalizeCompass16Direction, 'VRB', /supported abbreviation/);
  assertDirectionValueRejected(normalizeCompass16Direction, 'CALM', /supported abbreviation/);
  assertDirectionValueRejected(normalizeCompass16Direction, 'constructor', /supported abbreviation/);
  assertDirectionValueRejected(normalizeCompass16Direction, '', /supported abbreviation/);
  assertDirectionValueRejected(normalizeCompass16Direction, null, /supported abbreviation/);
  assertDirectionValueRejected(normalizeDegreeDirection, -0.01, /between 0 and 360/);
  assertDirectionValueRejected(convertDegreesToCompass16, -0.01, /between 0 and 360/);
  assertDirectionValueRejected(convertDegreesToCompass16, 360.01, /between 0 and 360/);
}

/**
 * <summary>
 * Verifies all four configured wind-direction behaviors have the intended HomeKit output format and conversion.
 * </summary>
 * @returns {void}
 */
function windDirectionUnitsExposeDirectAndConvertedRepresentations() {
  const registry = createDefaultWeatherUnitRegistry(createHapDouble());
  const directDegrees = registry.get('°');
  const directCompass = registry.get('compass16');
  const compassToDegrees = registry.get('compass16->°');
  const degreesToCompass = registry.get('°->compass16');

  assert.equal(directDegrees.characteristicProps.format, 'float');
  assert.equal(directDegrees.normalize(20), 20);
  assertDirectionValueRejected(directDegrees.normalize, -1, /between 0 and 360/);
  assert.equal(directCompass.characteristicProps.format, 'string');
  assert.equal(directCompass.normalize('NNE'), 'NNO');
  assert.equal(compassToDegrees.characteristicProps.format, 'float');
  assert.equal(compassToDegrees.characteristicProps.unit, 'arcdegrees');
  assert.equal(compassToDegrees.normalize('SSW'), 202.5);
  assert.equal(degreesToCompass.characteristicProps.format, 'string');
  assert.equal(degreesToCompass.normalize(292.5), 'WNW');
}

test('compass sector centers round-trip across all Dutch directions', compassCentersRoundTripAcrossAllDirections);
test('degree conversion uses exact 16-point compass boundaries', degreeConversionUsesCorrectSectorBoundaries);
test('international compass aliases normalize to Dutch notation', internationalCompassAliasesNormalizeToDutch);
test('invalid direction values are rejected instead of becoming north', invalidDirectionValuesAreRejected);
test('wind direction units expose direct and converted representations', windDirectionUnitsExposeDirectAndConvertedRepresentations);
