'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');

const { createDefaultWeatherUnitRegistry } = require('../lib/units/weather-unit-registry');

/**
 * <summary>
 * Creates deterministic UUID support for inspecting the production WMO definition without loading Homebridge.
 * </summary>
 * @returns {object} Minimal HAP namespace containing a stable UUID generator.
 */
function createHapDouble() {
  return {
    uuid: {
      /**
       * <summary>
       * Converts one production UUID seed into a deterministic readable test value.
       * </summary>
       * @param {string} seed Stable UUID seed generated by the unit registry.
       * @returns {string} Deterministic test UUID.
       */
      generate(seed) {
        return `uuid:${seed}`;
      },
    },
  };
}

/**
 * <summary>
 * Verifies the provider-neutral WMO unit accepts every integer code from 0 through 99 rather than only one
 * provider's subset, while keeping -1 as the explicit unavailable value.
 * </summary>
 * @returns {void}
 */
function wmoUnitAcceptsCompleteCodeRange() {
  const definition = createDefaultWeatherUnitRegistry(createHapDouble()).get('WMO');

  assert.equal(definition.neutralValue, -1);
  for (let code = 0; code <= 99; code += 1) {
    assert.equal(definition.normalize(code), code);
  }

  /**
   * <summary>
   * Attempts to normalize a WMO code above the complete two-digit range.
   * </summary>
   * @returns {void}
   */
  function normalizeOverflowingCode() {
    definition.normalize(100);
  }

  /**
   * <summary>
   * Attempts to normalize a fractional value that cannot represent a discrete WMO code.
   * </summary>
   * @returns {void}
   */
  function normalizeFractionalCode() {
    definition.normalize(4.5);
  }

  assert.throws(normalizeOverflowingCode, /above the supported range/);
  assert.throws(normalizeFractionalCode, /integer/);
}

test('WMO unit accepts the complete provider-neutral code range', wmoUnitAcceptsCompleteCodeRange);
